version: '3.8'

services:
  postgres:
    image: ankane/pgvector  # Includes pgvector pre-installed
    container_name: pgvector-db
    restart: always
    environment:
      POSTGRES_USER: rag_user
      POSTGRES_PASSWORD: rag_pass
      POSTGRES_DB: rag_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
